In [1]:
import sys
sys.path.append('/home/tks32/james_work/QUIP/build/linux_x86_64_gfortran')
import _quippy
import quippy
import numpy as np
f = open("ip.parms.SW.xml", "r")
gap_xml = f.read()
#print(gap_xml)
#pot = _quippy.f90wrap_potential_initialise(args_str='IP SW', param_str=gap_xml)
pot = quippy.potential_module.Potential(args_str='IP SW', param_str=gap_xml)

In [2]:
from ase.build import bulk

In [3]:
si = bulk("Si", cubic=True)
si.rattle()

In [4]:
calc = quippy.potential.potential(args_str='IP SW', param_str=gap_xml)

In [5]:
calc.calculate(atoms=si)

got here 1 <class 'NoneType'>
got here 2 <class 'quippy.atoms_types_module.Atoms'>
got here 3 <class 'quippy.atoms_types_module.Atoms'>
got here 4 <class 'quippy.atoms_types_module.Atoms'>


In [8]:
calc.get_forces(si)

array([[ 0.00450003,  0.00190741, -0.01946682],
       [-0.02856475, -0.0123701 ,  0.01699403],
       [-0.03227304, -0.0226717 ,  0.00138498],
       [ 0.00201925,  0.0031367 ,  0.01824051],
       [ 0.00503503,  0.02140316,  0.0245583 ],
       [ 0.01240667,  0.0108892 , -0.01699513],
       [ 0.02042636,  0.01874499, -0.0382288 ],
       [ 0.01645046, -0.02103965,  0.01351292]])

In [6]:
# test the converter

f_si = quippy.convert.ase_to_fortran(ase_atoms=si)

got here 1 <class 'NoneType'>
got here 2 <class 'quippy.atoms_types_module.Atoms'>
got here 3 <class 'quippy.atoms_types_module.Atoms'>
got here 4 <class 'quippy.atoms_types_module.Atoms'>


In [7]:
f_si.pos

array([[ 4.96714153e-04,  1.35902303e+00,  1.57921282e-03,
         1.35804256e+00,  2.71524196e+00,  4.07193771e+00,
         2.71409198e+00,  4.07227422e+00],
       [-1.38264301e-04,  1.35726585e+00,  2.71576743e+00,
         4.07203658e+00, -1.91328024e-03,  1.35648717e+00,
         2.71358770e+00,  4.07256753e+00],
       [ 6.47688538e-04,  1.35726586e+00,  2.71453053e+00,
         4.07203427e+00,  2.71327508e+00,  4.07281425e+00,
         1.46564877e-03,  1.35607525e+00]])

In [8]:
f_si.is_periodic

array([1, 1, 1], dtype=int32)

In [9]:
f_si.z

array([14, 14, 14, 14, 14, 14, 14, 14], dtype=int32)

In [10]:
force = np.zeros((3, len(si)), order='F')
pot.calc(f_si, force=force)

(-34.67980409680041, 0)

In [11]:
print(np.copy(force.T))

[[ 0.00450003  0.00190741 -0.01946682]
 [-0.02856475 -0.0123701   0.01699403]
 [-0.03227304 -0.0226717   0.00138498]
 [ 0.00201925  0.0031367   0.01824051]
 [ 0.00503503  0.02140316  0.0245583 ]
 [ 0.01240667  0.0108892  -0.01699513]
 [ 0.02042636  0.01874499 -0.0382288 ]
 [ 0.01645046 -0.02103965  0.01351292]]


## try if the converter wokrs on a fortran atoms as argument of it

In [12]:
# easy when it is the same length
qsi = quippy.atoms_types_module.Atoms(len(si), si.cell.T)

In [13]:
qsi

In [14]:
qsi.pos

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
quippy.convert.ase_to_fortran(ase_atoms=si, fortran_atoms=qsi)

got here 3 <class 'quippy.atoms_types_module.Atoms'>
got here 4 <class 'quippy.atoms_types_module.Atoms'>


In [16]:
qsi.pos

array([[ 4.96714153e-04,  1.35902303e+00,  1.57921282e-03,
         1.35804256e+00,  2.71524196e+00,  4.07193771e+00,
         2.71409198e+00,  4.07227422e+00],
       [-1.38264301e-04,  1.35726585e+00,  2.71576743e+00,
         4.07203658e+00, -1.91328024e-03,  1.35648717e+00,
         2.71358770e+00,  4.07256753e+00],
       [ 6.47688538e-04,  1.35726586e+00,  2.71453053e+00,
         4.07203427e+00,  2.71327508e+00,  4.07281425e+00,
         1.46564877e-03,  1.35607525e+00]])

In [17]:
# start from None
qsi_1 = None

In [18]:
qsi_1

In [19]:
quippy.convert.ase_to_fortran(ase_atoms=si, fortran_atoms=qsi_1)

got here 1 <class 'NoneType'>
got here 2 <class 'quippy.atoms_types_module.Atoms'>
got here 3 <class 'quippy.atoms_types_module.Atoms'>
got here 4 <class 'quippy.atoms_types_module.Atoms'>


In [21]:
type(qsi_1)

NoneType

In [20]:
qsi_1.pos

AttributeError: 'NoneType' object has no attribute 'pos'

In [4]:
qsi = quippy.atoms_types_module.Atoms(len(si), si.cell.T)
qsi.pos[:] = si.positions.T
qsi.is_periodic[:] = si.pbc
qsi.z[:] = si.numbers

In [5]:
force = np.zeros((3, len(si)), order='F')
pot.calc(qsi, force=force)

(-34.67980409680041, 0)

In [6]:
np.copy(force.T)

array([[ 0.00450003,  0.00190741, -0.01946682],
       [-0.02856475, -0.0123701 ,  0.01699403],
       [-0.03227304, -0.0226717 ,  0.00138498],
       [ 0.00201925,  0.0031367 ,  0.01824051],
       [ 0.00503503,  0.02140316,  0.0245583 ],
       [ 0.01240667,  0.0108892 , -0.01699513],
       [ 0.02042636,  0.01874499, -0.0382288 ],
       [ 0.01645046, -0.02103965,  0.01351292]])

In [7]:
qsi.properties.get_key(1)[0].strip()     # thsi is a byte string now

b'Z'

In [8]:
[qsi.properties.get_key(i)[0] for i in range(1, qsi.properties.n + 2)]

[b'Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

In [9]:

qsi.properties.get_array('pos', shape)
#(2, 13, 51198992) the alst one is a pointer

NameError: name 'shape' is not defined

In [10]:
quippy.dictionary_module.Dictionary??

In [27]:
shape

array([3, 8, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [28]:
import f90wrap.runtime

In [32]:
f90wrap.arraydata.get_array?

In [ ]:
# array_shape = np.zeros(10, order='F', dtype=np.int32)
# array_ndim, array_type, array_handle = \
#     qsi.properties.get_array('pos', array_shape)

pos = f90wrap.runtime.get_array(f90wrap.runtime.sizeof_fortran_t,
                        qsi.properties._handle,
                        _quippy.f90wrap_dictionary_get_array,
                        "pos")

In [11]:
qsi.properties.get_type_and_size("pos")[0]

TypeError: get_type_and_size() missing 1 required positional argument: 'thesize2'

In [12]:
qsi.properties.get_type_and_size?

In [15]:
import ase

In [16]:
ase.calculators.calculator

<module 'ase.calculators.calculator' from '/home/tks32/.local/lib/python3.6/site-packages/ase/calculators/calculator.py'>

In [19]:
ase.calculators.calculator.__mro__

AttributeError: module 'ase.calculators.calculator' has no attribute '__mro__'

In [21]:
quippy.potential_module.Potential?

In [25]:
pot.calc?

In [26]:
ase_atoms = bulk("Si", cubic=True)

In [40]:
ase_atoms.numbers.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False