In [1]:
import sys
sys.path.append('/home/tks32/james_work/QUIP/build/linux_x86_64_gfortran')
import _quippy
import quippy
import numpy as np

In [2]:
_quippy

<module '_quippy' from '/home/tks32/james_work/QUIP/build/linux_x86_64_gfortran/_quippy.cpython-36m-x86_64-linux-gnu.so'>

In [3]:
quippy

<module 'quippy' from '/home/tks32/james_work/QUIP/build/linux_x86_64_gfortran/quippy/__init__.py'>

In [4]:
a =  quippy.atoms_types_module.Atoms(10, np.eye(3))

In [5]:
a

In [6]:
a.lattice

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
_quippy.f90wrap_atoms__array__lattice(a._handle)

(2, 12, array([3, 3, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), 40366160)

In [8]:
a._handle

array([40366096,        0], dtype=int32)

In [9]:
a.pos

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
a.pos[:] = 1

In [11]:
a.pos

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
a.n

10

In [13]:
len(a)

TypeError: object of type 'Atoms' has no len()

In [ ]:
#_quippy.f90wrap_potential_initialise(args_str='IP SW', param_str='')

In [14]:
a.acc

ValueError: array is NULL

In [16]:
a.add_property?

In [17]:
quippy.table_module.Table?

In [18]:
quippy.atoms_types_module.Table?

In [25]:
a.add_property?

In [26]:
a.

array([[[32, 32, 32, 32, 32, 32, 32, 32, 32, 32],
        [32, 32, 32, 32, 32, 32, 32, 32, 32, 32],
        [32, 32, 32, 32, 32, 32, 32, 32, 32, 32],
        [32, 32, 32, 32, 32, 32, 32, 32, 32, 32],
        [32, 32, 32, 32, 32, 32, 32, 32, 32, 32],
        [32, 32, 32, 32, 32, 32, 32, 32, 32, 32],
        [32, 32, 32, 32, 32, 32, 32, 32, 32, 32],
        [32, 32, 32, 32, 32, 32, 32, 32, 32, 32],
        [32, 32, 32, 32, 32, 32, 32, 32, 32, 32],
        [32, 32, 32, 32, 32, 32, 32, 32, 32, 32]]], dtype=uint8)

<module '_quippy' from '/home/tks32/james_work/QUIP/build/linux_x86_64_gfortran/_quippy.cpython-36m-x86_64-linux-gnu.so'>

In [ ]:
quippy.potential_module.Potential("IP SW")

In [ ]:
quippy.potential_module.Potential??